use super::default_value;
use super::LuaGenerator;
use crate::parser::ast::*;

impl LuaGenerator {
    pub(crate) fn new() -> Self {
        Self {
            source: String::new(),
            indent: 0,
            proctype_names: Vec::new(),
            current_proctype: None,
            global_vars: std::collections::HashSet::new(),
            inlines: std::collections::HashMap::new(),
        }
    }

    /// Recursively collect all VarDecl statements from a proctype body,
    /// including inside if/do/atomic/d_step blocks.
    pub(crate) fn collect_var_decls(stmts: &[Stmt]) -> Vec<&VarDecl> {
        let mut result = Vec::new();
        for stmt in stmts {
            match stmt {
                Stmt::VarDecl(vd) => result.push(vd),
                Stmt::VarDecls(vds) => result.extend(vds.iter()),
                Stmt::For { init, body, .. } => {
                    if let Stmt::VarDecl(vd) = init.as_ref() {
                        result.push(vd);
                    }
                    for s in body {
                        result.extend(Self::collect_var_decls(std::slice::from_ref(s)));
                    }
                }
                Stmt::If(guards) | Stmt::Do(guards) => {
                    for g in guards {
                        result.extend(Self::collect_var_decls(&g.body));
                    }
                }
                Stmt::Atomic(body, _) | Stmt::DStep(body, _) => {
                    result.extend(Self::collect_var_decls(body));
                }
                _ => {}
            }
        }
        result
    }

    pub(crate) fn emit(&mut self, line: &str) {
        if !line.is_empty() {
            self.source.push_str(&"    ".repeat(self.indent));
            self.source.push_str(line);
        }
        self.source.push('\n');
    }

    pub(crate) fn emit_header(&mut self) {
        self.emit("-- Generated by spin-rs Lua code generator");
        self.emit("-- Runtime: mlua 5.4");
        self.emit("");
        self.emit("-- Channel operations (Rust FFI)");
        self.emit("local chan_send = _spin_chan_send");
        self.emit("local chan_recv = _spin_chan_recv");
        self.emit("local chan_len = _spin_chan_len");
        self.emit("local chan_full = _spin_chan_full");
        self.emit("local chan_empty = _spin_chan_empty");
        self.emit("local assert = _spin_assert");
        self.emit("local printf = _spin_printf");
        self.emit("local state_hash = _spin_state_hash");
        self.emit("");

        self.emit("-- State initialization");
        self.emit("-- Called once to create the initial state vector");
        self.emit("function _spin_init_state()");
        self.indent += 1;
    }

    pub(crate) fn emit_state_layout(&mut self, model: &PromelaModel) {
        // Collect all global and local variable declarations
        let mut lines = Vec::new();
        // Track which names are global for unprefixed access in expr_to_lua
        self.global_vars.clear();
        for decl in &model.declarations {
            match decl {
                TopLevel::GlobalVar(v) => {
                    self.global_vars.insert(v.name.clone());
                    if let Some(arr_size) = v.array_size {
                        if arr_size > 0 {
                            // Emit array as Lua table: {0, 0, ...}
                            let default = default_value(&v.var_type);
                            let elems = vec![default.as_str(); arr_size as usize].join(", ");
                            lines.push(format!("    state.{} = {{{}}}", v.name, elems));
                        } else {
                            let default = default_value(&v.var_type);
                            lines.push(format!("    state.{} = {}", v.name, default));
                        }
                    } else if let Some(init_expr) = &v.init {
                        let init_str = self.expr_to_lua(init_expr);
                        lines.push(format!("    state.{} = {}", v.name, init_str));
                    } else {
                        let default = default_value(&v.var_type);
                        lines.push(format!("    state.{} = {}", v.name, default));
                    }
                }
                TopLevel::Proctype(p) => {
                    let count = p.pid.map(|n| n as usize).unwrap_or(1);
                    for instance in 0..count {
                        let prefix = if instance == 0 && count == 1 {
                            p.name.clone()
                        } else {
                            format!("{}_{}", p.name, instance)
                        };
                        // Per-proctype done flag and step counter for guard body
                        lines.push(format!("    state._done_{} = false", prefix));
                        lines.push(format!("    state._step_{} = 0", prefix));
                        // Proctype parameters (prefixed with proctype name for uniqueness)
                        for param in &p.parameters {
                            let default = default_value(&param.var_type);
                            lines
                                .push(format!("    state.{}_{} = {}", prefix, param.name, default));
                        }
                        // Local variable declarations from body (prefixed with proctype name)
                        let local_vars = Self::collect_var_decls(&p.body);
                        for vd in local_vars {
                            if let Some(arr_size) = vd.array_size {
                                if arr_size > 0 {
                                    let default = default_value(&vd.var_type);
                                    let elems =
                                        vec![default.as_str(); arr_size as usize].join(", ");
                                    lines.push(format!(
                                        "    state.{}_{} = {{{}}}",
                                        prefix, vd.name, elems
                                    ));
                                } else if let Some(init_expr) = &vd.init {
                                    let init_str = self.expr_to_lua(init_expr);
                                    lines.push(format!(
                                        "    state.{}_{} = {}",
                                        prefix, vd.name, init_str
                                    ));
                                } else {
                                    let default = default_value(&vd.var_type);
                                    lines.push(format!(
                                        "    state.{}_{} = {}",
                                        prefix, vd.name, default
                                    ));
                                }
                            } else if let Some(init_expr) = &vd.init {
                                let init_str = self.expr_to_lua(init_expr);
                                lines.push(format!(
                                    "    state.{}_{} = {}",
                                    prefix, vd.name, init_str
                                ));
                            } else {
                                let default = default_value(&vd.var_type);
                                lines.push(format!(
                                    "    state.{}_{} = {}",
                                    prefix, vd.name, default
                                ));
                            }
                        }
                    }
                }
                TopLevel::ChanDecl { name, .. } => {
                    self.global_vars.insert(name.clone());
                    lines.push(format!("    state.{} = nil", name));
                }
                TopLevel::ChannelArray { name, size, .. } => {
                    // Don't add to global_vars — array channels are accessed as name_N
                    for i in 0..*size {
                        lines.push(format!("    state.{}_{} = nil", name, i));
                    }
                }
                _ => {}
            }
        }

        // Count processes for initialization
        let active_count: usize = model
            .declarations
            .iter()
            .map(|d| match d {
                TopLevel::Proctype(p) if p.active => p.pid.map(|n| n as usize).unwrap_or(1),
                _ => 0,
            })
            .sum();

        self.emit("    local state = {}");
        self.emit(&format!("    state._nr_pr = {}", active_count));
        self.emit("    state._nr_qs = 0");
        // Add _done_init flag if there's an init block
        if model
            .declarations
            .iter()
            .any(|d| matches!(d, TopLevel::Init(_)))
        {
            self.emit("    state._done_init = false");
        }
        for line in &lines {
            self.emit(line);
        }

        self.indent -= 1;
        self.emit("    return state");
        self.emit("end");
        self.emit("");
    }

    pub(crate) fn emit_proctypes(&mut self, model: &PromelaModel) {
        // First pass: collect inline definitions
        self.inlines.clear();
        for decl in &model.declarations {
            if let TopLevel::Inline(inline) = decl {
                self.inlines.insert(inline.name.clone(), inline.clone());
            }
        }

        for decl in &model.declarations {
            match decl {
                TopLevel::Proctype(p) => {
                    let count = if p.active {
                        p.pid.map(|n| n as usize).unwrap_or(1)
                    } else {
                        1
                    };
                    for instance in 0..count {
                        self.emit_proctype(p, instance);
                    }
                }
                TopLevel::Init(i) => {
                    // init block: runs once at startup
                    self.emit("-- init block");
                    self.emit("function _spin_transitions_init(state)");
                    self.indent += 1;
                    self.emit("    if state._done_init then return {} end");
                    self.emit("    local transitions = {}");
                    self.emit_stmts(&i.body, 0);
                    self.emit("    -- Mark init as done after first execution");
                    self.emit("    table.insert(transitions, {");
                    self.indent += 1;
                    self.emit("        guard = function() return true end,");
                    self.emit("        effect = function(s) s._done_init = true end,");
                    self.emit("        label = \"init:done\",");
                    self.indent -= 1;
                    self.emit("    })");
                    self.emit("    return transitions");
                    self.indent -= 1;
                    self.emit("end");
                    self.emit("");
                }
                TopLevel::NeverClaim(n) => {
                    self.emit("-- never claim");
                    self.emit("function _spin_transitions_never(state)");
                    self.indent += 1;
                    self.emit("    local transitions = {}");
                    self.emit_stmts(&n.body, 0);
                    self.emit("    return transitions");
                    self.indent -= 1;
                    self.emit("end");
                    self.emit("");
                }
                TopLevel::Ltl(l) => {
                    self.emit(&format!(
                        "-- LTL: {} = {}",
                        l.name.as_deref().unwrap_or("(unnamed)"),
                        l.formula
                    ));
                }
                TopLevel::Inline(i) => {
                    self.emit(&format!(
                        "-- inline: {}({}) (expansion deferred)",
                        i.name,
                        i.parameters.join(", ")
                    ));
                }
                TopLevel::CCode(code, _) => {
                    self.emit("-- embedded c_code (executed as Lua)");
                    self.emit("_spin_c_code([===[");
                    self.emit(code);
                    self.emit("]===])");
                }
                _ => {}
            }
        }
    }

    pub(crate) fn emit_proctype(&mut self, p: &ProctypeDef, instance: usize) {
        let (prefix, fn_name) = if instance == 0 && p.pid.map(|n| n as usize).unwrap_or(1) == 1 {
            // Single instance: keep original naming
            (p.name.clone(), format!("_spin_transitions_{}", p.name))
        } else {
            // Multi-instance: include instance number
            (
                format!("{}_{}", p.name, instance),
                format!("_spin_transitions_{}_{}", p.name, instance),
            )
        };
        self.proctype_names.push(fn_name.clone());
        self.current_proctype = Some(prefix.clone());

        self.emit(&format!(
            "-- Proctype: {} (instance {}, active: {})",
            p.name, instance, p.active
        ));
        self.emit(&format!("function {}(state)", fn_name));
        self.indent += 1;
        // Set _pid for this process instance
        self.emit(&format!("    state._pid = {}", instance));
        // Check done flag - if set, this process is done (break was executed)
        self.emit(&format!(
            "    if state._done_{} then return {{}} end",
            prefix
        ));
        self.emit("    local transitions = {}");
        self.emit("");

        // Emit transition table based on control flow
        self.emit_stmts(&p.body, 0);

        self.emit("    return transitions");
        self.indent -= 1;
        self.emit("end");
        self.emit("");
        self.current_proctype = None;
    }
}
