//! Lua code generator: compiles Promela IR into Lua scripts.
//!
//! The generated Lua is loaded by the mlua runtime and called by the
//! verification engine for model-specific transition enumeration.

use crate::parser::ast::*;

/// Generated Lua code components.
#[derive(Debug, Clone)]
pub struct GeneratedLua {
    /// The full Lua source as a string.
    pub source: String,
    /// Per-proctype transition enumerator names.
    pub proctype_fn_names: Vec<String>,
}

/// Compile a Promela model into Lua source code.
pub fn generate(model: &PromelaModel) -> GeneratedLua {
    let mut g = LuaGenerator::new();
    g.emit_header();
    g.emit_state_layout(model);
    g.emit_proctypes(model);
    g.emit_trailer();
    g.finish()
}

struct LuaGenerator {
    source: String,
    indent: usize,
    proctype_names: Vec<String>,
}

impl LuaGenerator {
    fn new() -> Self {
        Self {
            source: String::new(),
            indent: 0,
            proctype_names: Vec::new(),
        }
    }

    fn emit(&mut self, line: &str) {
        if !line.is_empty() {
            self.source.push_str(&"    ".repeat(self.indent));
            self.source.push_str(line);
        }
        self.source.push('\n');
    }

    fn emit_header(&mut self) {
        self.emit("-- Generated by spin-rs Lua code generator");
        self.emit("-- Runtime: mlua 5.4");
        self.emit("");
        self.emit("-- Channel operations (Rust FFI)");
        self.emit("local chan_send = _spin_chan_send");
        self.emit("local chan_recv = _spin_chan_recv");
        self.emit("local chan_len = _spin_chan_len");
        self.emit("local chan_full = _spin_chan_full");
        self.emit("local chan_empty = _spin_chan_empty");
        self.emit("local assert = _spin_assert");
        self.emit("local printf = _spin_printf");
        self.emit("local state_hash = _spin_state_hash");
        self.emit("");

        self.emit("-- State initialization");
        self.emit("-- Called once to create the initial state vector");
        self.emit("function _spin_init_state()");
        self.indent += 1;
    }

    fn emit_state_layout(&mut self, model: &PromelaModel) {
        // Collect all global variables
        let mut lines = Vec::new();
        for decl in &model.declarations {
            match decl {
                TopLevel::GlobalVar(v) => {
                    let default = default_value(&v.var_type);
                    lines.push(format!("    state.{} = {}", v.name, default));
                }
                TopLevel::Proctype(p) => {
                    // Proctype local variables will be per-process in state
                    for param in &p.parameters {
                        let default = default_value(&param.var_type);
                        lines.push(format!(
                            "    state.{}_p{}_{} = {}",
                            "", p.name, param.name, default
                        ));
                    }
                }
                _ => {}
            }
        }

        // Count processes for initialization
        let active_count: usize = model
            .declarations
            .iter()
            .filter(|d| matches!(d, TopLevel::Proctype(p) if p.active))
            .count();

        self.emit("    local state = {}");
        self.emit(&format!("    state._nr_pr = {}", active_count));
        self.emit("    state._nr_qs = 0");
        for line in &lines {
            self.emit(line);
        }

        self.indent -= 1;
        self.emit("    return state");
        self.emit("end");
        self.emit("");
    }

    fn emit_proctypes(&mut self, model: &PromelaModel) {
        for decl in &model.declarations {
            match decl {
                TopLevel::Proctype(p) => {
                    self.emit_proctype(p);
                }
                TopLevel::NeverClaim(n) => {
                    self.emit("-- never claim");
                    self.emit("function _spin_transitions_never(state)");
                    self.indent += 1;
                    self.emit(&format!("    -- {} states in never claim", n.body.len()));
                    self.emit("    return {}");
                    self.indent -= 1;
                    self.emit("end");
                    self.emit("");
                }
                TopLevel::Ltl(l) => {
                    self.emit(&format!(
                        "-- LTL: {} = {}",
                        l.name.as_deref().unwrap_or("(unnamed)"),
                        l.formula
                    ));
                }
                _ => {}
            }
        }
    }

    fn emit_proctype(&mut self, p: &ProctypeDef) {
        let fn_name = format!("_spin_transitions_{}", p.name);
        self.proctype_names.push(fn_name.clone());

        self.emit(&format!("-- Proctype: {} (active: {})", p.name, p.active));
        self.emit(&format!("function {}(state)", fn_name));
        self.indent += 1;
        self.emit("    local transitions = {}");
        self.emit("");

        // Emit transition table based on control flow
        self.emit_stmts(&p.body, 0);

        self.emit("    return transitions");
        self.indent -= 1;
        self.emit("end");
        self.emit("");
    }

    fn emit_stmts(&mut self, stmts: &[Stmt], depth: usize) {
        for stmt in stmts {
            match stmt {
                Stmt::Assignment { target, value, .. } => {
                    let expr_str = self.expr_to_lua(value);
                    self.emit(&format!("    -- T{}: {}", depth, target));
                    self.emit("    table.insert(transitions, {");
                    self.indent += 1;
                    self.emit("    guard = function() return true end,");
                    self.emit(&format!(
                        "    effect = function(s) s.{} = {} end",
                        target, expr_str
                    ));
                    self.indent -= 1;
                    self.emit("    })");
                }
                Stmt::If(guards) => {
                    self.emit_guards("if", guards, depth);
                }
                Stmt::Do(guards) => {
                    // For do/od, emit all guards as transitions (loop back)
                    self.emit_guards("do", guards, depth);
                }
                Stmt::Goto(label, _) => {
                    self.emit(&format!("    -- goto {}", label));
                    self.emit("    -- TODO: handle goto in codegen");
                }
                Stmt::Break(_) => {
                    self.emit("    -- break (loop exit)");
                }
                Stmt::Assert(expr, _) => {
                    let e = self.expr_to_lua(expr);
                    self.emit(&format!("    -- assert({})", e));
                    self.emit("    table.insert(transitions, {");
                    self.indent += 1;
                    self.emit(&format!("    guard = function(s) return {} end,", e));
                    self.emit("    effect = function(s) assert({}, 'assertion failed') end");
                    self.indent -= 1;
                    self.emit("    })");
                }
                Stmt::Printf(fmt, args, _) => {
                    let args_str: Vec<String> = args.iter().map(|a| self.expr_to_lua(a)).collect();
                    let args_concat = args_str.join(", ");
                    self.emit(&format!("    printf(\"{}\", {})", fmt, args_concat));
                }
                Stmt::Send {
                    channel,
                    target,
                    args,
                    ..
                } => {
                    let args_str: Vec<String> = args.iter().map(|a| self.expr_to_lua(a)).collect();
                    let args_concat = args_str.join(", ");
                    match target {
                        SendTarget::Ident(id) => {
                            self.emit("    table.insert(transitions, {");
                            self.indent += 1;
                            self.emit(&format!(
                                "    guard = function(s) return not chan_full(s.{}) end,",
                                channel
                            ));
                            self.emit(&format!(
                                "    effect = function(s) chan_send(s.{}, {}, {}) end",
                                channel, id, args_concat
                            ));
                            self.indent -= 1;
                            self.emit("    })");
                        }
                        SendTarget::Value(e) => {
                            let val = self.expr_to_lua(e);
                            self.emit("    table.insert(transitions, {");
                            self.indent += 1;
                            self.emit(&format!(
                                "    guard = function(s) return not chan_full(s.{}) end,",
                                channel
                            ));
                            self.emit(&format!(
                                "    effect = function(s) chan_send(s.{}, {}, {}) end",
                                channel, val, args_concat
                            ));
                            self.indent -= 1;
                            self.emit("    })");
                        }
                    }
                }
                Stmt::Recv {
                    channel, target, ..
                } => match target {
                    RecvTarget::VarList(vars) => {
                        let vars_str = vars.join(", ");
                        self.emit("    table.insert(transitions, {");
                        self.indent += 1;
                        self.emit(&format!(
                            "    guard = function(s) return not chan_empty(s.{}) end,",
                            channel
                        ));
                        self.emit(&format!(
                            "    effect = function(s) {}, _ = chan_recv(s.{}) end",
                            vars_str, channel
                        ));
                        self.indent -= 1;
                        self.emit("    })");
                    }
                    RecvTarget::Eval(expr) => {
                        let e = self.expr_to_lua(expr);
                        self.emit("    table.insert(transitions, {");
                        self.indent += 1;
                        self.emit(&format!(
                            "    guard = function(s) return true end, -- poll [{}]",
                            e
                        ));
                        self.emit("    effect = function(s) end");
                        self.indent -= 1;
                        self.emit("    })");
                    }
                    _ => {}
                },
                Stmt::Skip(_) => {
                    self.emit("    table.insert(transitions, { guard = function() return true end, effect = function(s) end })");
                }
                Stmt::Run(name, args, _) => {
                    let args_str: Vec<String> = args.iter().map(|a| self.expr_to_lua(a)).collect();
                    self.emit(&format!("    -- run {}({})", name, args_str.join(", ")));
                    self.emit("    -- TODO: dynamic process creation");
                }
                Stmt::Atomic(body, _) => {
                    self.emit("    -- atomic block (all-or-nothing transitions)");
                    self.emit_stmts(body, depth + 1);
                }
                Stmt::DStep(body, _) => {
                    self.emit("    -- d_step (deterministic step)");
                    self.emit_stmts(body, depth + 1);
                }
                Stmt::VarDecl(v) => {
                    let default = default_value(&v.var_type);
                    self.emit(&format!("    -- var decl: {} = {}", v.name, default));
                }
                Stmt::Expr(e, _) => {
                    let es = self.expr_to_lua(e);
                    self.emit(&format!("    -- expr: {}", es));
                }
                Stmt::Unless { body, handler, .. } => {
                    self.emit("    -- unless statement");
                    self.emit_stmts(body, depth + 1);
                    self.emit("    -- unless handler:");
                    self.emit_stmts(handler, depth + 1);
                }
                Stmt::Label(label, _) => {
                    self.emit(&format!("    -- label: {}", label));
                }
            }
        }
    }

    fn emit_guards(&mut self, kind: &str, guards: &[Guard], _depth: usize) {
        for (i, guard) in guards.iter().enumerate() {
            let cond_str = match &guard.condition {
                Some(e) => self.expr_to_lua(e),
                None => "true".to_string(),
            };

            self.emit(&format!("    -- {} guard {}: {}", kind, i, cond_str));
            self.emit("    table.insert(transitions, {");
            self.indent += 1;
            self.emit(&format!("    guard = function(s) return {} end,", cond_str));
            self.emit("    effect = function(s)");
            self.indent += 1;
            for s in &guard.body {
                // Recursive call for body statements
                match s {
                    Stmt::Assignment { target, value, .. } => {
                        let v = self.expr_to_lua(value);
                        self.emit(&format!("    s.{} = {}", target, v));
                    }
                    Stmt::Break(_) => {
                        self.emit("    -- break");
                    }
                    Stmt::Goto(label, _) => {
                        self.emit(&format!("    -- goto {}", label));
                    }
                    Stmt::Assert(expr, _) => {
                        let e = self.expr_to_lua(expr);
                        self.emit(&format!("    assert({}, 'assertion failed')", e));
                    }
                    Stmt::Send {
                        channel, target, ..
                    } => {
                        let id = match target {
                            SendTarget::Ident(id) => id.clone(),
                            SendTarget::Value(_) => "expr".to_string(),
                        };
                        self.emit(&format!("    chan_send(s.{}, {}, ...)", channel, id));
                    }
                    Stmt::Recv {
                        channel, target, ..
                    } => {
                        if let RecvTarget::VarList(vars) = target {
                            let vs = vars.join(", ");
                            self.emit(&format!("    {}, _ = chan_recv(s.{})", vs, channel));
                        }
                    }
                    Stmt::Skip(_) => {}
                    Stmt::Expr(e, _) => {
                        self.emit(&format!("    -- {}", self.expr_to_lua(e)));
                    }
                    _ => {
                        self.emit("    -- (stmt not yet inlined in codegen)");
                    }
                }
            }
            self.indent -= 1;
            self.emit("    end,");
            // Add depth information
            self.emit(&format!("    label = \"{}:guard{}\",", kind, i));
            self.indent -= 1;
            self.emit("    })");
        }
    }

    fn emit_trailer(&mut self) {
        self.emit("-- Main transition dispatcher");
        self.emit("-- Called by Rust engine to enumerate transitions");
        self.emit("function _spin_get_transitions(state)");
        self.indent += 1;
        self.emit("    local all = {}");
        let names = self.proctype_names.clone();
        for name in names {
            self.emit(&format!("    local t = {}(state)", name));
            self.emit("    for _, tr in ipairs(t) do");
            self.emit("        table.insert(all, tr)");
            self.emit("    end");
        }
        self.emit("    return all");
        self.indent -= 1;
        self.emit("end");
        self.emit("");

        self.emit("-- State hashing callback");
        self.emit("function _spin_hash(state)");
        self.indent += 1;
        self.emit("    return state_hash(state)");
        self.indent -= 1;
        self.emit("end");
    }

    fn expr_to_lua(&self, expr: &Expression) -> String {
        match expr {
            Expression::IntLit(n) => n.to_string(),
            Expression::StringLit(s) => format!("\"{}\"", s),
            Expression::BoolLit(b) => b.to_string(),
            Expression::Ident(name) => format!("s.{}", name),
            Expression::ArrayAccess { name, index } => {
                format!("s.{}[{}]", name, self.expr_to_lua(index))
            }
            Expression::UnaryOp { op, expr: e } => {
                let op_str = match op {
                    UnaryOp::Not => "not ",
                    UnaryOp::BitNot => "~",
                    UnaryOp::Neg => "-",
                    UnaryOp::Always => "[]",
                    UnaryOp::Eventually => "<>",
                    UnaryOp::Next => "X",
                };
                format!("{}{}", op_str, self.expr_to_lua(e))
            }
            Expression::BinaryOp { op, left, right } => {
                let op_str = match op {
                    BinaryOp::Add => " + ",
                    BinaryOp::Sub => " - ",
                    BinaryOp::Mul => " * ",
                    BinaryOp::Div => " / ",
                    BinaryOp::Mod => " % ",
                    BinaryOp::Eq => " == ",
                    BinaryOp::Neq => " ~= ",
                    BinaryOp::Lt => " < ",
                    BinaryOp::Le => " <= ",
                    BinaryOp::Gt => " > ",
                    BinaryOp::Ge => " >= ",
                    BinaryOp::And => " and ",
                    BinaryOp::Or => " or ",
                    BinaryOp::BitAnd => " & ",
                    BinaryOp::BitOr => " | ",
                    BinaryOp::BitXor => " // ",
                    BinaryOp::Shl => " << ",
                    BinaryOp::Shr => " >> ",
                    BinaryOp::Impl => " -> ",
                    BinaryOp::BiImpl => " <-> ",
                    BinaryOp::Until => " U ",
                    BinaryOp::Release => " V ",
                };
                format!(
                    "{}{}{}",
                    self.expr_to_lua(left),
                    op_str,
                    self.expr_to_lua(right)
                )
            }
            Expression::FuncCall { name, args } => {
                let args_str: Vec<String> = args.iter().map(|a| self.expr_to_lua(a)).collect();
                format!("{}({})", name, args_str.join(", "))
            }
            Expression::Len(_) => "0".to_string(),
            Expression::Full(ch) => format!("chan_full(s.{})", ch),
            Expression::Empty(ch) => format!("chan_empty(s.{})", ch),
            Expression::NFull(_) => "false".to_string(),
            Expression::NEmpty(_) => "false".to_string(),
            Expression::Enabled(_) => "true".to_string(),
            Expression::Timeout => "false".to_string(),
            Expression::RemoteRef { name, .. } => format!("s.{}", name),
            Expression::RecordAccess { record, field } => {
                format!("{}[\"{}\"]", self.expr_to_lua(record), field)
            }
            Expression::ChannelSend { channel, target } => {
                format!("s.{}[{}]", channel, self.expr_to_lua(target))
            }
            Expression::ChannelPoll { channel, .. } => {
                format!("not chan_empty(s.{})", channel)
            }
        }
    }

    fn finish(self) -> GeneratedLua {
        GeneratedLua {
            source: self.source,
            proctype_fn_names: self.proctype_names,
        }
    }
}

fn default_value(var_type: &VarType) -> String {
    match var_type {
        VarType::Bit | VarType::Bool | VarType::Byte => "0".to_string(),
        VarType::Short | VarType::Int | VarType::Unsigned(_) => "0".to_string(),
        VarType::Chan => "nil".to_string(),
        VarType::Mtype => "0".to_string(),
        VarType::Named(_) => "nil".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser;

    #[test]
    fn test_generate_basic_proctype() {
        let source = "active proctype P() { byte x; x = 1; }";
        let model = parser::parse(source).unwrap();
        let lua = generate(&model);
        assert!(lua.source.contains("function _spin_init_state"));
        assert!(lua.source.contains("function _spin_transitions_P"));
        assert!(lua.source.contains("function _spin_get_transitions"));
    }

    #[test]
    fn test_generate_with_guards() {
        let source = "active proctype P() { if :: (x > 0) -> y = 1 :: else -> y = 0 fi }";
        let model = parser::parse(source).unwrap();
        let lua = generate(&model);
        assert!(lua.source.contains("guard"));
        assert!(lua.source.contains("effect"));
    }

    #[test]
    fn test_generate_ltl() {
        let source = "ltl p0 { [](x == 0) }\nactive proctype P() { x = 1; }";
        let model = parser::parse(source).unwrap();
        let lua = generate(&model);
        assert!(lua.source.contains("LTL: p0"));
    }
}
